---
title: "Homework 2"
author: "Vasili Fokaidis"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
```

## Problem 1

First, define a path to the dataset.

```{r}
path_to_data = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx"
```


Read the Mr. Trashwheel dataset.

```{r}
trashwheel_df =
  read_xlsx(
          path = path_to_data,
          sheet = "Mr. Trash Wheel",
          range = cell_cols("A:N"))%>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
          sports_balls = round(sports_balls),
          sports_balls = as.integer(sports_balls)
  )
```

Read precipitation data! For 2018 and 2017

```{r}
precip_2018 =
  read_excel("./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2018 Precipitation",
    skip = 1
  ) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2018) %>%
  relocate(year)

precip_2017 =
  read_excel(
    "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
    sheet = "2017 Precipitation",
    skip = 1
  ) %>%
  janitor::clean_names() %>%
  drop_na(month) %>%
  mutate(year = 2017) %>%
  relocate(year)
```



